### PR TITLE
Update topic.html for subscribe to receive messages

### PR DESCRIPTION
**Pull request by xiao5286**
Update the subscribe topic to receive messages.

### CODE REVIEW

**Comment by xiao5286** [comment]
@fmvilas Created a PR for updating the subscribe topic to receive messages.

**Review by fmvilas — APPROVED** [review]

**Comment by fmvilas** [comment]
Awesome! Thanks for the PR, @xiao5286!

**Comment by fmvilas** [comment]
I just [published it to npm](https://www.npmjs.com/package/asyncapi-docgen) and also updated editor.asyncapi.org. Thank you!

**Comment by xiao5286** [comment]
@fmvilas I have updated docgen and been able to see my change. Thanks.

**Comment by fmvilas** [comment]
You're welcome! FYI, we're gonna deprecate docgen soon, in favor of this package: https://github.com/asyncapi/generator. The [editor](editor.asyncapi.org) is already using it and contains the fix you did in this PR.

**Comment by xiao5286** [comment]
@fmvilas Thank you for the updates. Does the new generator support or plan to support async api v1.2 very soon?

**Comment by fmvilas** [comment]
@xiao5286 I'm happy that you ask. All efforts are going to be focused on the generator from now on. The editor uses the generator package, so yes, we'll add support soon :)

**Pull request merged**
